### ISSUE TITLE
vitess_build Fetch Updated Vitess error

### ISSUE THREAD

**Issue by frouioui** [vitessio/arewefastyet#122]
## Description

The following error output was caught during the execution of a microbenchmark task. The error seems to occur due to an undefined variable though all required variables (`vitess_git_repo` and `vitess_git_version`) were declared.

**Error:**
```
TASK [vitess_build : Fetch Updated Vitess] *************************************
fatal: [147.75.101.73]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: the inline if-expression on line 1 evaluated to false and no else section was defined.\n\nThe error appears to be in '/exec/<exec id>/ansible/roles/vitess_build/tasks/install_vitess.yml': line 15, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name: Fetch Updated Vitess\n      ^ here\n"}
```

**Configuration:**
```yaml
...
ansible-inventory-files: microbench_inventory.yml
ansible-playbook-files: microbench.yml
ansible-root-directory: /root/arewefastyet/ansible/
...
```
